select *
from ( 
select 'categoria' as tabela, count(1) as linhas from categoria
union select 'cfg_boleto_api' as tabela, count(1) as linhas from cfg_boleto_api
union select 'com_assistente' as tabela, count(1) as linhas from com_assistente
union select 'com_atendimento' as tabela, count(1) as linhas from com_atendimento
union select 'com_cliente' as tabela, count(1) as linhas from com_cliente
union select 'com_cliente_endereco' as tabela, count(1) as linhas from com_cliente_endereco
union select 'com_config' as tabela, count(1) as linhas from com_config
union select 'com_contrato' as tabela, count(1) as linhas from com_contrato
union select 'com_fatura' as tabela, count(1) as linhas from com_fatura
union select 'com_produto' as tabela, count(1) as linhas from com_produto
union select 'com_produto_material' as tabela, count(1) as linhas from com_produto_material
union select 'com_servico' as tabela, count(1) as linhas from com_servico
union select 'com_servico_comissao' as tabela, count(1) as linhas from com_servico_comissao
union select 'com_venda' as tabela, count(1) as linhas from com_venda
union select 'com_venda_item' as tabela, count(1) as linhas from com_venda_item
union select 'com_vendedor' as tabela, count(1) as linhas from com_vendedor
union select 'conta_importar' as tabela, count(1) as linhas from conta_importar
union select 'ctb_area' as tabela, count(1) as linhas from ctb_area
union select 'ctb_balancete_rel' as tabela, count(1) as linhas from ctb_balancete_rel
union select 'ctb_ccusto' as tabela, count(1) as linhas from ctb_ccusto
union select 'ctb_conta' as tabela, count(1) as linhas from ctb_conta
union select 'ctb_conta_saldo' as tabela, count(1) as linhas from ctb_conta_saldo
union select 'ctb_historico_padrao' as tabela, count(1) as linhas from ctb_historico_padrao
union select 'ctb_lancamento' as tabela, count(1) as linhas from ctb_lancamento
union select 'ctb_lancamento_item' as tabela, count(1) as linhas from ctb_lancamento_item
union select 'ctb_plano_conta' as tabela, count(1) as linhas from ctb_plano_conta
union select 'ctb_razao_rel' as tabela, count(1) as linhas from ctb_razao_rel
union select 'fin_adiantamento_cfg' as tabela, count(1) as linhas from fin_adiantamento_cfg
union select 'fin_cancelamento' as tabela, count(1) as linhas from fin_cancelamento
union select 'fin_cnab_previa_tmp' as tabela, count(1) as linhas from fin_cnab_previa_tmp
union select 'fin_cob_config' as tabela, count(1) as linhas from fin_cob_config
union select 'fin_cobranca' as tabela, count(1) as linhas from fin_cobranca
union select 'fin_config' as tabela, count(1) as linhas from fin_config
union select 'fin_conta_corrente_tbl' as tabela, count(1) as linhas from fin_conta_corrente_tbl
union select 'fin_conta_financeira' as tabela, count(1) as linhas from fin_conta_financeira
union select 'fin_conta_financeira_mes' as tabela, count(1) as linhas from fin_conta_financeira_mes
union select 'fin_conta_financeira_mov' as tabela, count(1) as linhas from fin_conta_financeira_mov
union select 'fin_conta_financeira_rel' as tabela, count(1) as linhas from fin_conta_financeira_rel
union select 'fin_conta_financeira_transf' as tabela, count(1) as linhas from fin_conta_financeira_transf
union select 'fin_despesa' as tabela, count(1) as linhas from fin_despesa
union select 'fin_docto_tipo' as tabela, count(1) as linhas from fin_docto_tipo
union select 'fin_fluxo_caixa_mes' as tabela, count(1) as linhas from fin_fluxo_caixa_mes
union select 'fin_grupo' as tabela, count(1) as linhas from fin_grupo
union select 'fin_lancamento' as tabela, count(1) as linhas from fin_lancamento
union select 'fin_lancamento_baixa' as tabela, count(1) as linhas from fin_lancamento_baixa
union select 'fin_lancamento_ccusto' as tabela, count(1) as linhas from fin_lancamento_ccusto
union select 'fin_lancamento_tmp' as tabela, count(1) as linhas from fin_lancamento_tmp
union select 'fin_nfe' as tabela, count(1) as linhas from fin_nfe
union select 'fin_orgao_publico' as tabela, count(1) as linhas from fin_orgao_publico
union select 'fin_parametro' as tabela, count(1) as linhas from fin_parametro
union select 'fin_planejamento' as tabela, count(1) as linhas from fin_planejamento
union select 'fin_planejamento_item' as tabela, count(1) as linhas from fin_planejamento_item
union select 'fin_prestador_servicos' as tabela, count(1) as linhas from fin_prestador_servicos
union select 'fin_tipo_pagamento' as tabela, count(1) as linhas from fin_tipo_pagamento
union select 'fin_xml_temp' as tabela, count(1) as linhas from fin_xml_temp
union select 'fis_classe' as tabela, count(1) as linhas from fis_classe
union select 'fis_imposto' as tabela, count(1) as linhas from fis_imposto
union select 'fis_imposto_pagamento' as tabela, count(1) as linhas from fis_imposto_pagamento
union select 'fis_nota_fiscal' as tabela, count(1) as linhas from fis_nota_fiscal
union select 'fis_nota_fiscal_imposto' as tabela, count(1) as linhas from fis_nota_fiscal_imposto
union select 'fop_cargo' as tabela, count(1) as linhas from fop_cargo
union select 'fop_departamento_tbl' as tabela, count(1) as linhas from fop_departamento_tbl
union select 'fop_dependente' as tabela, count(1) as linhas from fop_dependente
union select 'fop_evento' as tabela, count(1) as linhas from fop_evento
union select 'fop_evento_valor' as tabela, count(1) as linhas from fop_evento_valor
union select 'fop_folha' as tabela, count(1) as linhas from fop_folha
union select 'fop_funcionario' as tabela, count(1) as linhas from fop_funcionario
union select 'fop_lancamento' as tabela, count(1) as linhas from fop_lancamento
union select 'fop_parametro' as tabela, count(1) as linhas from fop_parametro
union select 'fop_tabela' as tabela, count(1) as linhas from fop_tabela
union select 'ged_docto' as tabela, count(1) as linhas from ged_docto
union select 'ged_docto_log' as tabela, count(1) as linhas from ged_docto_log
union select 'ged_tipo_docto' as tabela, count(1) as linhas from ged_tipo_docto
union select 'glb_empresa' as tabela, count(1) as linhas from glb_empresa
union select 'glb_empresa_socio' as tabela, count(1) as linhas from glb_empresa_socio
union select 'glb_lancamento_historico' as tabela, count(1) as linhas from glb_lancamento_historico
union select 'glb_parametro_segmento' as tabela, count(1) as linhas from glb_parametro_segmento
union select 'glb_seg_opcao' as tabela, count(1) as linhas from glb_seg_opcao
union select 'glb_unidade' as tabela, count(1) as linhas from glb_unidade
union select 'glb_usuario' as tabela, count(1) as linhas from glb_usuario
union select 'glb_usuario_empresa' as tabela, count(1) as linhas from glb_usuario_empresa
union select 'glb_usuario_parametro' as tabela, count(1) as linhas from glb_usuario_parametro
union select 'log_motorista' as tabela, count(1) as linhas from log_motorista
union select 'log_viagem' as tabela, count(1) as linhas from log_viagem
union select 'orc_orcamento' as tabela, count(1) as linhas from orc_orcamento
union select 'plano_conta_referencia' as tabela, count(1) as linhas from plano_conta_referencia
union select 'rel_resultado_financeiro' as tabela, count(1) as linhas from rel_resultado_financeiro
union select 'sup_compra' as tabela, count(1) as linhas from sup_compra
union select 'sup_compra_mov' as tabela, count(1) as linhas from sup_compra_mov
union select 'sup_config' as tabela, count(1) as linhas from sup_config
union select 'sup_estoque' as tabela, count(1) as linhas from sup_estoque
union select 'sup_estoque_fornecedor' as tabela, count(1) as linhas from sup_estoque_fornecedor
union select 'sup_estoque_imp' as tabela, count(1) as linhas from sup_estoque_imp
union select 'sup_estoque_mov' as tabela, count(1) as linhas from sup_estoque_mov
union select 'sup_estoque_rel' as tabela, count(1) as linhas from sup_estoque_rel
union select 'sup_fornecedor' as tabela, count(1) as linhas from sup_fornecedor
union select 'sup_material_fornecedor' as tabela, count(1) as linhas from sup_material_fornecedor
union select 'tbl_faturamento' as tabela, count(1) as linhas from tbl_faturamento
union select 'usuario_permissao' as tabela, count(1) as linhas from usuario_permissao
) x order by 2 desc

